"""Build duckv24/taaf-duck-v24.ipynb — v10 + the untried-ledger nudge (B32), nothing else.

WHY (notes/R28-goal-model-audit.md): 4/5 stuck levels hold a wrong or never-formed goal,
and 3/5 clears trace to a probe taken before the theory was finished. The nudge makes the
harness COUNT what was never tried on the current level and say so at analysis turns
8/16/24..., through the hint channel measured obeyed (sk48 7/7 on animation nudges).

RIG-VERIFIED before this build (localrig, qwen3-8b, 2026-08-24):
  - ft09 (MOUSE-only): ledger correctly SILENT for 34 turns (everything tried at turn 0)
  - ls20: fired at turn 8 exactly — "actions tried: RIGHT; NEVER tried: DOWN, LEFT, UP" —
    and the model pressed LEFT + DOWN within 4 actions of the nudge; turn 16 silent
    because everything was tried by then. Function-level teeth run at module import.

ATTRIBUTION: single change vs v10 (upscale stays 4, output stays uncapped, stock prompts).
Cell 12 embeds duckv24/ledger_patch.py VERBATIM (single source of truth) and calls apply().

Run:  python duckv24/build_notebook.py
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC_NB = REPO / "duckmod" / "taaf-duck-mod.ipynb"
OUT_NB = REPO / "duckv24" / "taaf-duck-v24.ipynb"
PATCH_SRC = REPO / "duckv24" / "ledger_patch.py"

OLD_SHARE = "jeroencottaar/taaf-kaggle-source-share"
NEW_SHARE = "jakobbrggen/taaf-kaggle-source-anim-20260807-anim"
OLD_DS = "driessmit1/vrfai-qwen3-6-27b-fp8-hf-snapshot"
NEW_DS = "jakobbrggen/qwen3-8-27b-fp8-hf-snapshot"

OLD_LOOP = """for command in json.loads((BUNDLE_DIR / "setup_commands.json").read_text()):
    print(f"taaf.kaggle: setup command: {command}", flush=True)"""

# Byte-identical to v10's rewrite (duckv21 carried the same block). ONE change lives in
# cell 12; this loop must keep v10's exact config: NO output cap, upscale 4.
NEW_LOOP = """for command in json.loads((BUNDLE_DIR / "setup_commands.json").read_text()):
    # duckv24: v10's model swap (R12 seam) and nothing else here. NO output cap (v9),
    # NO KV flag (v14), NO upscale change (v18/v23 both measured in-noise or worse).
    command = (
        command
        .replace("MODEL_OWNER = 'driessmit1'", "MODEL_OWNER = 'jakobbrggen'")
        .replace(
            "MODEL_SLUG = 'vrfai-qwen3-6-27b-fp8-hf-snapshot'",
            "MODEL_SLUG = 'qwen3-8-27b-fp8-hf-snapshot'",
        )
        .replace(
            "SERVED_MODEL_NAME = 'vrfai/Qwen3.6-27B-FP8'",
            "SERVED_MODEL_NAME = 'vrfai/Qwen3.8-27B-FP8'",
        )
    )
    assert "vrfai-qwen3-6-27b-fp8-hf-snapshot" not in command, "duckv24: model slug rewrite missed"
    assert "Qwen3.6-27B-FP8" not in command, "duckv24: served-name rewrite missed"
    assert "'LOCAL_ANALYZER_MAX_OUTPUT': '0'" in command, "duckv24: output must stay UNCAPPED"
    assert "'MULTIMODAL_UPSCALE': '4'" in command, "duckv24: upscale must stay 4 (v10 exact)"
    print(f"taaf.kaggle: setup command: {command}", flush=True)"""


def main() -> None:
    patch = PATCH_SRC.read_text(encoding="utf-8")
    assert "_ta.ToolAgent._animation_hint_line = _ledger_hint_line" in patch, (
        "ledger_patch: the class-attribute patch line is missing from apply()"
    )
    assert "TEETH FAIL" in patch and "_teeth()" in patch, "ledger_patch: teeth missing"
    assert "def apply():" in patch, "ledger_patch: apply() entry missing"

    # cell 12 = the patch module verbatim + arm it. The module's own _teeth() runs at
    # exec time IN THE KERNEL, before the benchmark starts (R8: teeth in-kernel).
    cell12 = (
        "# duckv24 cell 12 - generated by build_notebook.py; source of truth is\n"
        "# duckv24/ledger_patch.py (embedded verbatim below, teeth run on exec).\n"
        + patch
        + "\nprint(apply(), flush=True)\n"
    )

    nb = json.loads(SRC_NB.read_text(encoding="utf-8"))

    c6 = "".join(nb["cells"][6]["source"])
    assert OLD_DS in c6 and OLD_SHARE in c6, "cell 6: expected dataset refs not found"
    nb["cells"][6]["source"] = c6.replace(OLD_SHARE, NEW_SHARE).replace(OLD_DS, NEW_DS)

    c8 = "".join(nb["cells"][8]["source"])
    assert OLD_LOOP in c8, "cell 8: expected setup loop not found"
    nb["cells"][8]["source"] = c8.replace(OLD_LOOP, NEW_LOOP)

    nb["cells"][12]["source"] = cell12

    OUT_NB.parent.mkdir(parents=True, exist_ok=True)
    OUT_NB.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    print(f"wrote {OUT_NB} ({OUT_NB.stat().st_size} bytes)")

    # --- self-check ---
    src = json.loads(SRC_NB.read_text(encoding="utf-8"))
    out = json.loads(OUT_NB.read_text(encoding="utf-8"))
    diff = [i for i in range(len(src["cells"])) if src["cells"][i]["source"] != out["cells"][i]["source"]]
    assert diff == [6, 8, 12], f"unexpected diff cells: {diff}"
    for idx in diff:
        compile("".join(out["cells"][idx]["source"]), f"cell{idx}", "exec")
    print(f"syntax OK: cells {diff} compile")

    o8 = "".join(out["cells"][8]["source"])
    o12 = "".join(out["cells"][12]["source"])
    assert "'MULTIMODAL_UPSCALE': '8'" not in o8, "v24 must not carry the upscale change"
    assert "'LOCAL_ANALYZER_MAX_OUTPUT': '768'" not in o8, "v24 must not cap output"
    assert patch in o12, "cell 12 does not embed ledger_patch.py verbatim"

    print("self-check OK: cells [6, 8, 12]; v10 config exact + ledger nudge armed in cell 12")
    print(f"cell 12 embeds {PATCH_SRC.name} verbatim ({len(patch)} chars)")


if __name__ == "__main__":
    main()
