"""Build the HYBRID single-file Kaggle agent: the competition's own sample
agent as the default actor, with `compete.play` pre-empting it on games a
driver signature claims.

    ./.venv/Scripts/python.exe kaggle/goose_extract.py     # once, or after a
    ./.venv/Scripts/python.exe kaggle/bundle_hybrid.py     # starter-kit update

Same mechanism as `kaggle/bundle.py` -- every module is embedded zlib+base64
and registered in `sys.modules` BEFORE its source is exec'd (dataclasses
resolve their module at class-creation) -- plus one more embedded module: the
sample agent extracted from the starter kit's reference notebook by
`kaggle/goose_extract.py`.  Its class becomes `GooseAgent`, which
`kaggle/adapter_hybrid.py`'s `MyAgent` inherits.

**Output goes to the STARTER KIT, not into this repo.**  The bundle contains a
third party's MIT source (StochasticGoose, Tufa Labs); this repo is MIT-0, and
writing their code into it would relicense their work.  The rationale, and the
honest caveat that the drivers claim almost nothing on the hidden set, are in
`kaggle/adapter_hybrid.py`'s docstring.

`kaggle/bundle.py` and `kaggle/my_agent.py` are untouched by this script --
the two candidates are built side by side so the submission choice stays open.
"""
from __future__ import annotations

import base64
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STARTER = Path(r"C:\Users\Vampi\Desktop\ARC-AGI-3-Kaggle-Starter")
GOOSE = STARTER / "reference" / "stochastic-goose" / "goose_agent.py"
OUT = STARTER / "agent" / "my_agent_hybrid.py"
ADAPTER = ROOT / "kaggle" / "adapter_hybrid.py"

# Dependency order matters: each module's imports must already be in
# sys.modules when it executes.
MODULES = ["identity", "perception", "signals", "trace", "discover", "plan",
           "gate", "cover", "swap", "haul", "maze", "dial", "skewer",
           "tape", "bridge", "sorter", "ferry", "claw", "mirror", "twin",
           "roller", "scoring", "compete"]

HEADER = '''\
"""ARC Prize 2026 HYBRID submission agent -- GENERATED by kaggle/bundle_hybrid.py.

The competition's own sample agent (StochasticGoose -- Tufa Labs, MIT,
github.com/DriesSmit/ARC3-solution, shipped in the starter kit's reference
notebook) plays every game; `compete.play` with fourteen measured whole-game
drivers pre-empts it on games a driver signature claims.  Our half's source of
truth: github.com/Sahasawatt/arc-agi-3-agent
"""
from __future__ import annotations

import base64 as _b64
import queue
import random
import sys as _sys
import threading
import time
import types as _types
import zlib as _zlib
from typing import Any

import numpy as np

from arcengine import FrameData, GameAction, GameState
from agents.agent import Agent

'''

LOADER = '''
def _load(name, blob):
    m = _types.ModuleType(name)
    src = _zlib.decompress(_b64.b64decode(blob)).decode("utf-8")
    _sys.modules[name] = m   # BEFORE exec: dataclasses resolve their own
    #                          module through sys.modules at class-creation
    exec(compile(src, name + ".py", "exec"), m.__dict__)
    return m

'''


def _embed(name: str, src: str) -> str:
    blob = base64.b64encode(zlib.compress(src.encode("utf-8"), 9)).decode()
    return f'{name} = _load("{name}", "{blob}")\n'


def main() -> None:
    if not GOOSE.exists():
        raise SystemExit(
            f"{GOOSE} is missing -- run kaggle/goose_extract.py first")
    parts = [HEADER, LOADER]
    for name in MODULES:
        parts.append(_embed(name, (ROOT / f"{name}.py").read_text(encoding="utf-8")))
    parts.append(_embed("_goose", GOOSE.read_text(encoding="utf-8")))
    parts.append("GooseAgent = _goose.MyAgent\n")
    adapter = ADAPTER.read_text(encoding="utf-8")
    mark = "# --- BUNDLE BODY ---"
    parts.append("\n" + adapter.split(mark, 1)[1].lstrip("\n"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
