"""Build the single-file Kaggle agent from the repo's whole-game drivers.

    ./.venv/Scripts/python.exe kaggle/bundle.py

The competition's starter kit (`github.com/arcprize/ARC-AGI-3-Kaggle-Starter`)
splices ONE file -- `agent/my_agent.py` -- into the submission notebook, so
everything the agent needs must live in that file. This script embeds the agent's
modules verbatim (zlib+base64, because their sources contain every quoting
style) and appends the adapter class from `kaggle/adapter.py`.

The drivers are the source of truth; `kaggle/my_agent.py` is a build artifact
and is never edited by hand. Rebuild after any driver change.

The bundle carries the FULL agent -- `compete.play`, the rung machinery that
plays ls20 at 43% plus all six whole-game drivers. `play` drives an
environment directly and the Kaggle framework inverts control, so the
adapter runs it on a worker thread against a queue-backed proxy env; see
`kaggle/adapter.py`.
"""
from __future__ import annotations

import base64
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Dependency order matters: each module's imports must already be in
# sys.modules when it executes.
MODULES = ["identity", "perception", "signals", "trace", "discover", "plan",
           "gate", "cover", "swap", "haul", "maze", "dial", "skewer",
           "scoring", "compete"]
OUT = ROOT / "kaggle" / "my_agent.py"
ADAPTER = ROOT / "kaggle" / "adapter.py"

HEADER = '''\
"""ARC Prize 2026 submission agent -- GENERATED by kaggle/bundle.py, do not edit.

Six measured whole-game drivers (cover/swap/haul/maze/dial/skewer) behind
their reset-frame signatures, a random fallback for everything else. Source
of truth: github.com/Sahasawatt/arc-agi-3-agent
"""
from __future__ import annotations

import base64 as _b64
import queue
import random
import sys as _sys
import threading
import types as _types
import zlib as _zlib
from typing import Any

import numpy as np

from arcengine import FrameData, GameAction, GameState
from agents.agent import Agent

'''

LOADER = '''
def _load(name, blob):
    m = _types.ModuleType(name)
    src = _zlib.decompress(_b64.b64decode(blob)).decode("utf-8")
    _sys.modules[name] = m   # BEFORE exec: dataclasses resolve their own
    #                          module through sys.modules at class-creation
    exec(compile(src, name + ".py", "exec"), m.__dict__)
    return m

'''


def main() -> None:
    parts = [HEADER, LOADER]
    for name in MODULES:
        src = (ROOT / f"{name}.py").read_text(encoding="utf-8")
        blob = base64.b64encode(zlib.compress(src.encode("utf-8"), 9)).decode()
        parts.append(f'{name} = _load("{name}", "{blob}")\n')
    adapter = ADAPTER.read_text(encoding="utf-8")
    # Drop the adapter's own header (everything above the MARK line) -- its
    # imports exist only so the file lints standalone.
    mark = "# --- BUNDLE BODY ---"
    parts.append("\n" + adapter.split(mark, 1)[1].lstrip("\n"))
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
